### ISSUE TITLE
how to compile it on Rapsberry PI ?

### ISSUE THREAD

**Issue by djsuszi** [ribbons/RemehaBoilerLogger#1]
there's now stupid questions,
but how to compile it ??

**Comment by ribbons** [comment]
Yes, sorry - I need to document that :smile: 

From memory, you'll need to do something along these lines:

```
sudo apt-get install libboost-test-dev cppcheck git cmake
git clone https://github.com/ribbons/RemehaBoilerLogger.git
cd RemehaBoilerLogger
mkdir build
cd build
cmake ..
make
```

Let me know if that works or if you hit an issue compiling.
