### ISSUE TITLE
celenta 25ds to iobroker

### ISSUE THREAD

**Issue by j3sk0** [ribbons/RemehaBoilerLogger#3]
Hi

I would like to use the data in iobroker for my Celenta Ds25. How is the data recorded via serial USB? ftdi? an easy way for me would be mqtt.

**Comment by ribbons** [comment]
From memory, I'm using a TTL serial to RS232 converter to connect between the boiler and a USB serial adaptor to connect to the Pi.  I don't know if your boiler has the same kind of interface though.  The project as it stands doesn't use MQTT - I have thought about adding MQTT so I could display the boiler state in Home Assistant but it hasn't got any further than thoughts at the moment :smile:
