### ISSUE TITLE
Parameters convert.pl

### ISSUE THREAD

**Issue by camstar01** [ribbons/RemehaBoilerLogger#6]
Hi,

I am trying to use convert.pl to convert a Remeha CMIX xml. I cannot figure out the second parameter. What is a language file? 

Thanks,

Chris.

**Comment by ribbons** [comment]
In the copy of Recom I downloaded there are two folders which contain the XML files which convert.pl is expecting:
 - config: One of these (appropriate to the boiler in question) should be passed as the first parameter
 - language: One of these (appropriate for the language to display, e.g. I used language-en.xml) should be passed as the second parameter.

Hope that helps, do you think this should be documented in the README?

**Comment by camstar01** [comment]
That was helpfull! I'm on linux, so could not install the recom app, just copied the cmix.xml (for my equipment) to my linux box. Now the language file is also copied. I'm still not out of the woods, I have the cmix.xml, the language file, but I thought the third parameter was the output of the script xml. But it seems the third parameter has to be present in the cmix.xml. I don't know what to put there. The script states: "Third parameter should be configuration name"

**Comment by camstar01** [comment]
Quick update: configuration name should probably be one of the elements like parameter, sample or any other configuration entry in the source xml. Although parameter results in an error "Use of unitialized value in hash element at line 70" while sample produces a output file.

**Comment by camstar01** [comment]
In my type of equipment (c-Mix (P2)) there are four types of configurations:
- parameter (not working) - Use of unitialized value in hash element at line 70
- sample (working)
- status (working)
- identification (not working) - Can't use an undefined value as an ARRAY reference at ./convert.pl at line 87
So I have to do some investigation into the script

I have modified the corresponding cpp files.

The cmix does not suppert counters as it is a control device (multi zone controller) and not an actual heating device.

**Comment by ribbons** [comment]
Line 70 is looking up language strings from numbers in the configuration file, sounds like some of these aren't defined for your device, wonder if there is some special-casing that goes on in Recom for these values, probably worth seeing what it does.

Line 87 is related to handling the 'special data conversion' numbered methods - the script currently only handles method numbers 5 and 6 as that's the only ones encountered so far, you'll need to work out what the method you've encountered does.

**Comment by camstar01** [comment]
Thanks! I have included the cmix.xml file (for reference). I will look into your remarks! 
[Cmix_P2.xml.zip](https://github.com/ribbons/RemehaBoilerLogger/files/13854410/Cmix_P2.xml.zip)

**Comment by camstar01** [comment]
There is also a special data conversion number 4....

**Comment by ribbons** [comment]
Are there any changes that would be worthwhile adding to the project based on your experience with trying to add support for your device - e.g. specific documentation enhancements or improvements to convert.pl or do you reckon I should go ahead and close this issue?

**Comment by camstar01** [comment]
Hi Matt,
It is a bit of a steep learning curve, but you did some great work. The description of the parameters  of the convert script were not clear to me because I did not install the Recom software. It is still not clear to me what the difference is in the 4,5 and 6 type. So i’m still finding out how it is supposed to work. After the convert script I have to find out what the eprom file is for. So I do appreciate the work you put into this, but the lack of documentation in the code makes it difficult.You can close the issue. It was the only way to get into contact. Thanks for the help so far!
Kind regards
Chris

**Comment by ribbons** [comment]
I just pushed a couple of commits to make things a tiny bit easier for others in future:
6d18e4d35c635d8f5b gives a clearer error message from convert.pl when a 'special data' conversion method is encountered that isn't yet implemented
6d7c500ecb8a540dd7 extends convert.pl to be able to use text strings included inline in config XML files as well as the numbered language strings.

The second means that I can run it without errors against the 'parameter' configuration for Cmix_P2.xml from my old copy of Recom.  I think there are still other differences between the configuration files that will need additional work but I've started you off :smile:
